#!/bin/bash

IFS='%'
DATADIR=data
cd $DATADIR
ls *.txt > ../tmp
cd ..

while read file
do
  cd $DATADIR
  n=`grep -Ec 'You (Bought|Sold)' $file`
  if [ $n -eq 0 ]; then
    cd ..
    continue
  fi
  DATE=`grep -A1 "TRADE DATE" $file | awk '{print $4}'`
  DATE=`grep -A1 "TRADE DATE" $file | grep -E '[0-9]{2}-[0-9]{2}-[0-9]{2}' | awk '{print $4}'`
  TRANS=`grep -E -A2 "You (Bought|Sold)" $file`
  SYMBOL=`grep -oE 'Symbol: [A-Z]{4}X' $file | awk '{print $2}'`
  AMOUNT=`grep -oE 'Principal Amount\s*[0-9]*,*[0-9]*\.[0-9]*' $file | awk '{print $3}'`
  #NSH=`grep -oE 'You (Bought|Sold)\s*[0-9]*\.[0-9]*' $file`
  NSH=`grep -E -A1 'You (Bought|Sold)' $file | grep -v 'at' | cut -c1-37 | grep -oE '[0-9]*\.[0-9]*'`
  ACTION=`grep -Eo 'You (Bought|Sold)' $file | awk '{print $2}'`
  PRICE=`grep -oE 'at\s*[0-9]*\.[0-9]*' $file | awk '{print $2}'`
  #echo -e "$file  $n "
  echo $DATE > t0
  echo $ACTION > t1
  echo $SYMBOL > t2
  echo $AMOUNT > t3
  echo $NSH > t4
  echo $PRICE >t5
  paste t0 t1 t2 t3 t4 t5 > tt
  cat tt
  rm t0 t1 t2 t3 t4 t5 tt
  cd ..
done < tmp
rm tmp
unset IFS

