DROP TABLE ACT;
CREATE TABLE ACT
(
CDS CHAR(14),
RTYPE CHAR(1),
SNAME VARCHAR(128), 
DNAME VARCHAR(64), 
CNAME VARCHAR(20), 
Enroll912 INT, 
NumTstTakr INT, 
AvgScrEng INT, 
AvgScrRead INT, 
AvgScrMath INT, 
AvgScrSci INT, 
NumGE21 INT, 
PctGE21 DOUBLE
);
LOAD DATA INFILE '2013_14_ACT.csv' INTO TABLE ACT FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
