DROP TABLES EnroAll, EnroUnd, EnroGra, EnroTot, EnroA;

CREATE TABLE EnroAll
(UNITID INT, EFALEVEL INT, LINE INT, SECTION INT, LSTUDY INT, XEFTOTLT INT, EFTOTLT INT, XEFTOTLM INT, EFTOTLM INT, XEFTOTLW INT, EFTOTLW INT, XEFAIANT INT, EFAIANT INT, XEFAIANM INT, EFAIANM INT, XEFAIANW INT, EFAIANW INT, XEFASIAT INT, EFASIAT INT, XEFASIAM INT, EFASIAM INT, XEFASIAW INT, EFASIAW INT, XEFBKAAT INT, EFBKAAT INT, XEFBKAAM INT, EFBKAAM INT, XEFBKAAW INT, EFBKAAW INT, XEFHISPT INT, EFHISPT INT, XEFHISPM INT, EFHISPM INT, XEFHISPW INT, EFHISPW INT, XEFNHPIT INT, EFNHPIT INT, XEFNHPIM INT, EFNHPIM INT, XEFNHPIW INT, EFNHPIW INT, XEFWHITT INT, EFWHITT INT, XEFWHITM INT, EFWHITM INT, XEFWHITW INT, EFWHITW INT, XEF2MORT INT, EF2MORT INT, XEF2MORM INT, EF2MORM INT, XEF2MORW INT, EF2MORW INT, XEFUNKNT INT, EFUNKNT INT, XEFUNKNM INT, EFUNKNM INT, XEFUNKNW INT, EFUNKNW INT, XEFNRALT INT, EFNRALT INT, XEFNRALM INT, EFNRALM INT, XEFNRALW INT, EFNRALW  INT);

LOAD DATA INFILE 'Enrollment_Race.csv' INTO TABLE EnroAll 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

CREATE TABLE EnroUnd # undergrad
(SELECT 
unitid, 
EFTOTLT as UND_EFTOTLT,
EFASIAT as UND_EFASIAT, 
EFNRALT as UND_EFNRALT
FROM EnroAll WHERE EFALEVEL=22);

CREATE TABLE EnroGra # grad
(SELECT 
unitid, 
EFTOTLT as GRA_EFTOTLT,
EFASIAT as GRA_EFASIAT, 
EFNRALT as GRA_EFNRALT
FROM EnroAll WHERE EFALEVEL=32);

CREATE TABLE EnroTot # total
(SELECT 
unitid, 
EFTOTLT as TOT_EFTOTLT,
EFASIAT as TOT_EFASIAT, 
EFNRALT as TOT_EFNRALT
FROM EnroAll WHERE EFALEVEL=21);

CREATE TABLE EnroA
SELECT EnroUnd.*, 
GRA_EFTOTLT, GRA_EFASIAT, GRA_EFNRALT
FROM EnroUnd LEFT JOIN EnroGra 
ON EnroUnd.unitid=EnroGra.unitid;

CREATE TABLE EnroRace
SELECT EnroA.*, 
TOT_EFTOTLT, TOT_EFASIAT, TOT_EFNRALT
FROM EnroA LEFT JOIN EnroTot
ON EnroA.unitid=EnroTot.unitid;

DROP TABLES EnroA, EnroUnd, EnroGra, EnroTot;
