DROP TABLE AP;
CREATE TABLE AP
(
CDS CHAR(14),
RTYPE CHAR(1),
Enroll912 INT, 
NumTstTakr INT, 
NumScr1 INT, 
NumScr2 INT, 
NumScr3 INT, 
NumScr4 INT, 
NumScr5 INT
);
LOAD DATA INFILE '2013_14_AP.csv' INTO TABLE AP FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
